name: ADD_TO_PROJECT

on:
  issues:
    types:
      - opened
      - transferred
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  Exec:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@91ab1ce99159178a744e75cd17aed2da50f294ec
        with:
          project-url: https://github.com/orgs/camunda/projects/23/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
