name: ADD_TO_PROJECT

on:
  issues:
    types:
      - opened
      - transferred
      - labeled
  pull_request:
    types:
      - opened
      - labeled

jobs:
  Exec:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@d79571d8737ce0caa0120f44b15f2bc8f193d11a
        with:
          project-url: https://github.com/orgs/camunda/projects/23/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
